refactor: support for @hapi/joi 16.1.1
evanshortiss/express-joi-validation pull request #22
Opened 2019-09-18 22:19 UTC by danhowitt

@hapi/joi 16.1.1 doesn't have a root validate method `Joi.validate()`. Instead call validate on the schema. 

All tagged versions of @hapi/Joi have a validate method on the schema object so should be backwards compatible.

2019-09-19 13:48 UTC, evanshortiss commented
@danhowitt thanks for fixing this.

Can you remove the extra formatting your IDE added? This makes reviewing easier.

2019-09-19 13:48 UTC, evanshortiss commented on express-joi-validation.d.ts
> +  Params = 'params',
By "extra formatting" I mean these commas and the semi-colons @danhowitt

2019-09-19 13:49 UTC, evanshortiss requested changes
Changes per formatting comments

2019-09-20 08:55 UTC, danhowitt commented
Sure, i'll get on it. Sorry default setup for formatting kicked in

2019-09-20 09:01 UTC, danhowitt commented
Should be good to go.

2019-09-20 19:22 UTC, evanshortiss commented
@danhowitt thanks. Will get a release out soon. It'll be a major release since it changes the API a little

2019-09-20 19:22 UTC, merged