Narrow down ExpressJoiError type to assume the Joi.ValidationResult is an error
evanshortiss/express-joi-validation pull request #46
Opened 2024-11-29 10:59 UTC by feclist

👋 

While writing some error handling middleware using ExpressJoiError I noticed that the type also includes the non-error type of the `Joi.ValidationResult`:
```ts
{
    error: undefined;
    warning?: ValidationError;
    value: TSchema;
}
```

I assume (and correct me if I'm wrong!) that the ExpressJoiError is only raised when the `Joi.ValidationResult` contains the error field. If that is true then `Extract`ing the error variant of the type will result in a more narrow type to use. 

Additionally I've also added the `TSchema` generic type on the ExpressJoiError that's passed into the `Joi.ValidationResult` to allow for more accurate handling when it comes to the schema that raised the error.

2024-12-09 04:43 UTC, evanshortiss requested changes
Great PR. Can you update to the suggested version number and I can do a release.

2024-12-09 04:43 UTC, evanshortiss commented on package.json
> +  "version": "5.0.2",
```suggestion
  "version": "5.1.0",
```

2024-12-11 10:11 UTC, feclist commented on package.json
> +  "version": "5.0.2",
Done 👍

2024-12-11 13:45 UTC, merged

2024-12-13 07:46 UTC, evanshortiss commented
Published as v6